---
title: "fDOM Interference Testing"
output:
  html_document:
    toc: no
    highlight: tango
editor_options:
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(dpi = 300)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)


source(here::here('R', '00_vis_custom.R'))
source(here::here('R', '00_load-packages.R'))
```

```{r load-data, include = FALSE, results = FALSE}

source(here::here('R', '02.2_load_all_data.R'))
source(here::here('R', 'interference', '03_fdom-load-wrangle-run.R'))
```

```{r fdom-multiplot, fig.width=6, fig.height=8, fig.cap = "Fluorescent dissolved organic carbon (fDOM) interference testing on the EXO Total Algae Sensor for chlorophyll-a RFU was conducted by Guana Tolomato Matanzas, Lake Superior, North Inlet-Winyah Bay, and Old Woman Creek NERRs. Standards were made using ambient water near each NERR and added to deonized water (A), and local ambient water (C). Differences in response of the combusted standards to the same ambient water source, from Guana Tolomato Matanzas NERR, was also tested (B)."}
fdom_multiplot
```
