---
title: "Turbidity Interference Testing"
output:
  html_document:
    toc: no
    highlight: tango
editor_options:
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(dpi = 300)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)


source(here::here('R', '00_vis_custom.R'))
source(here::here('R', '00_load-packages.R'))
```

Using data from GTM, NIW, and HEE reserves.

```{r load-data, include = FALSE, results = FALSE}

source(here::here('R', '02_load_data.R'))
source(here::here('R', '03_wrangle_data.R'))
source(here::here('R', 'interference', '02.1_turb-load-wrangle-run-gtm.R'))
source(here::here('R', 'interference', '02.2_turb-load-wrangle-run-niw.R'))
source(here::here('R', 'interference', '02.3_turb-load-wrangle-run-hee.R'))
```

# {.tabset .tabset-pills}

## GTMNERR
```{r, fig.cap = "Average turbidity (FNU) and chlorophyll fluorescence (RFU) from three separate trials conducted by the Guana Tolomato Matanzas NERR."}
turb_interf_gtm
```


## NIWNERR

```{r, fig.cap = "Average turbidity (FNU) and chlorophyll fluorescence (RFU) from three separate trials conducted by the North Inlet-Winyah Bay NERR."}
turb_interf_niw
```

## HEENERR

```{r, fig.cap = "Average turbidity (FNU) and chlorophyll fluorescence (RFU) from two separate trials conducted by the He'eia NERR."}
turb_interf_hee
```