---
title: "NERRS Chlorophyll Catalyst Project"
subtitle: Data Update Version 1
date: 'Created 2021-06-25 (updated: `r Sys.Date()`)'
output:
  html_document:
    toc: yes
    toc_float: yes
    df_print: paged
editor_options:
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(dpi = 120)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)

source(here::here('R', '00_vis_custom.R'))
source(here::here('R', '00_load-packages.R'))
```

<br>

<right><blockquote class="blockquote text-right">
  <p class="mb-0">The greatest value of a picture is when it forces us to notice what we never expected to see.</p>
  <footer class="blockquote-footer">John W. Tukey</footer>
</blockquote></right>


```{r load-data, include = FALSE, results = FALSE}

source(here::here('R', '02_load_data.R'))
source(here::here('R', '03_wrangle_data.R'))

```

Reserves with submissions this round:

```{r reserves-1}
unique(all$reserve_code)

```

Reserves with only ISCO data:
```{r reserves-2}
unique(isco$reserve_code)

```

Reserves with only tank data:
```{r reserves-3}
unique(tank$reserve_code)

```

# Current Data

```{r}
source(here::here('R', '04.1_all-figures.R'))

all_figure
```

## Current Data with reserves and the methods pulled out:

```{r}
all_reserve_method_figure
```

## All data with the three interference parameters {.tabset}

### Still

```{r all-interf}

fdom

turb

temp

```

### Interactive

```{r all-interf-interact}

ggplotly(all %>%
           filter(chlorophyll_rfu > 0) %>%
           ggplot(aes(x = chlorophyll_rfu, y = chla_ugl, group = reserve_code)) +
           geom_point(aes(color = fdom_qsu), size = 3) +
           scale_color_continuous(name = "fDOM QSU") +
           ggpubr::theme_classic2() +
           labs(x = 'Chlorophyll a RFU EXO',
                y = 'Chlorophyll a ug/L Extracted',
                title = "fDOM",
                caption = "Both Tank and ISCO Experiments"),
         tooltip = c("fdom_qsu", "chlorophyll_rfu", "chla_ugl", "reserve_code"))


ggplotly(all %>%
           filter(chlorophyll_rfu > 0 & turb < 240) %>%
           ggplot(aes(x = chlorophyll_rfu, y = chla_ugl, group = reserve_code)) +
           geom_point(aes(color = turb), size = 3) +
           scale_color_continuous(name = "Turbidity NTU")  +
           ggpubr::theme_classic2() +
           labs(x = 'Chlorophyll a RFU EXO',
                y = 'Chlorophyll a ug/L Extracted',
                title = "Turbidity", caption = "Both Tank and ISCO Experiments"),
         tooltip = c("turb", "chlorophyll_rfu", "chla_ugl", "reserve_code"))

ggplotly(all %>%
           filter(chlorophyll_rfu > 0) %>%
           ggplot(aes(x = chlorophyll_rfu, y = chla_ugl)) +
           geom_point(aes(color = temp), size = 3) +
           scale_color_gradient(name = 'Temperature C',
                                low="blue", high="red") +
           scale_color_continuous(name = expression(paste('Temperature ', "(", degree, "C)"))) +
           ggpubr::theme_classic2() +
           labs(x = 'Chlorophyll a RFU EXO',
                y = 'Chlorophyll a ug/L Extracted',
                title = "Temperature", caption = "Both Tank and ISCO Experiments"),
         tooltip = c("temp", "chlorophyll_rfu", "chla_ugl", "reserve_code"))

```